### ISSUE TITLE
Need a way to associate generic metadata on bam file

### ISSUE THREAD

**Issue by tnngh** [VertebrateResequencing/vr-pipe#24]
Currently, only sequencing stats and sex can be associated with a bam file as a vrpipe step.   We need a way to associate any metadata on a bam file without having to create a fofn with metadata as a datasource.  This allows easier chaining vrpipe setups without having to wait until one setup finishes before creating the next.

**Comment by sb10** [comment]
If you're writing your own steps, you can already associate whatever generic metadata you like.

Some our own steps may choose to ignore that metadata and not copy it across to the output file, but in that case either alter the step to copy over your desired metadata key, or write your own steps.
