### ISSUE TITLE
Need to ensure that bams are indexed before running gatk base quality recalibration

### ISSUE THREAD

**Issue by tnngh** [VertebrateResequencing/vr-pipe#25]
Revise GATK base quality recalibration (GATK v3.6+) pipeline such that it indexes the bams before the GATK step executes

**Comment by sb10** [comment]
Can you offer a pull request for this? Thanks!

**Comment by tnngh** [comment]
My apologies.  There are several versions of the vr-pipe repositories floating around.  I created these issues in the wrong one.
