### ISSUE TITLE
vrpipe server does not create dataelements

### ISSUE THREAD

**Issue by tnngh** [VertebrateResequencing/vr-pipe#26]
A shot in the dark.  We are able to run our vrpipe server without error, and create vrpipe Setups without error.  However, the DataElements are not created in the database.  There is no information in the server logs, vrpipe-logs, or vrpipe-submissions regarding an invalid DataSource.

What do you think may be the problem?  Or where would be a good place to start debugging?

**Comment by sb10** [comment]
Has it ever worked on other setups?

You can debug what's happening with the datasource using one of:

```
Debug a datasource method in production:
$ perl -I/path/to/vr-pipe/modules -MVRPipe -e '$ds = VRPipe::DataSource->get(id => shift); $si = $ds->_source_instance; $si->debug(1); $si->_generate_elements;' <datasource id>

Or run the full code path for the datasource:
$ perl -I/path/to/vr-pipe/modules -MVRPipe -e '$ds = VRPipe::DataSource->get(id => shift); $ds->elements(0, 1);' <datasource id>

Debug a stalled setup by triggering it:
$ perl -I/path/to/vr-pipe/modules -MVRPipe -Mstrict -we 'my $ps = VRPipe::PipelineSetup->get(id => shift); $ps->trigger(debug => 1);' <setup id>
```

For debugging purposes, sprinkle the code for the datasource you're using with print statements to see what's going on, to see where it gets stuck.

**Comment by tnngh** [comment]
This is a spurious issue with our development vrpipe server.  At first, the server did not create any DataElements for any of the 2 existing setups.  However, after several hours, the server eventually created the DataElements, and ran the jobs.  Then we created 2 new setups, and their DataElements were not picked up by the server for several hours again.  We were able to force the server to create the DataElements and run the jobs by explicitly triggering the setup via command:
````
perl -I/path/to/vr-pipe/modules -MVRPipe -Mstrict -we 'my $ps = VRPipe::PipelineSetup->get(id => shift); $ps->trigger();' <setup id>
````
There was very little load on the host running the development vrpipe server.

**Comment by sb10** [comment]
What are the details of the datasource? Which one, configured in what way? Perhaps there is some reason for the delay in creating the elements.

It's also possible you have some "bad" datasource handlers running, which are slow for some reason. Try stopping the server, making sure there are no handlers still running in LSF, and starting it again. Then add a new setup and see what happens.

**Comment by tnngh** [comment]
Fofn with metadata and genome chunking.    The vrpipe-server was restarted several times with no effect.  However, at present, new setups are automatically picked up by the vrpipe server within a few minutes.

**Comment by sb10** [comment]
Sounds like a bad datasource handler then. In future, if a manual trigger works it means you have something running in LSF which is trying but failing to update the datasource. Killing those processes should help, unless the problem is that updating the datasource takes so long (or uses so much memory?) that LSF kills the job.
