### ISSUE TITLE
Throttling DB connections

### ISSUE THREAD

**Issue by tnngh** [VertebrateResequencing/vr-pipe#27]
On our production vr-pipe server, we are experiencing quite a bit of "Too many connections" errors.  Our mysql server is set with max_connections <= 1000.  At present, we have several setups that spawn over 1000 short jobs, and we think that perhaps the handlers are all hitting the mysql server simultaneously.  We are manually deactivating setups so to avoid overloading vrpipe, and redesigning our jobs so that there are fewer but run longer, reducing the chance that the vrpipe handler hits the db.

Is it possible to configure vrpipe to throttle the number of jobs that vrpipe server spawns to coincide with the max connections set on mysql server?  

Should we simply increase the max connections on our mysql server, and if so, what is the sizing guide?

Below is the exception stack.

DBI Connection failed: DBI connect('database=[];host=[];port=[]','[]',...) failed: Too many connections at /nfs/team112/perlbrew/perls/perl-5.14.2-farm3/lib/site_perl/5.14.2/DBIx/Class/Storage/DBI.pm line 1395. at /nfs/team112/perlbrew/perls/perl-5.14.2-farm3/lib/site_perl/5.14.2/DBIx/Class/Schema.pm line 1080, <GEN33> line 16.
	DBIx::Class::Schema::throw_exception(VRPipe::Persistent::Schema=HASH(0x5d95728), "DBI Connection failed: DBI connect('database=[]"...) called at /nfs/team112/perlbrew/perls/perl-5.14.2-farm3/lib/site_perl/5.14.2/DBIx/Class/Storage.pm line 112
	DBIx::Class::Storage::throw_exception(DBIx::Class::Storage::DBI::mysql=HASH(0x98e44d8), "DBI Connection failed: DBI connect('database=pipe_production_"...) called at /nfs/team112/perlbrew/perls/perl-5.14.2-farm3/lib/site_perl/5.14.2/DBIx/Class/Storage/DBI.pm line 1455
	DBIx::Class::Storage::DBI::catch {...} ("DBI connect('database=[];host=[];port="...) called at /nfs/team112/perlbrew/perls/perl-5.14.2-farm3/lib/site_perl/5.14.2/Try/Tiny.pm line 106
	Try::Tiny::try(CODE(0x9d4de00), Try::Tiny::Catch=REF(0x9c41028)) called at /nfs/team112/perlbrew/perls/perl-5.14.2-farm3/lib/site_perl/5.14.2/DBIx/Class/Storage/DBI.pm line 1456
	DBIx::Class::Storage::DBI::_connect(DBIx::Class::Storage::DBI::mysql=HASH(0x98e44d8), "dbi:mysql:database=[];host=[];port=[]", "[]", "[]", HASH(0x9948790)) called at /nfs/team112/perlbrew/perls/perl-5.14.2-farm3/lib/site_perl/5.14.2/DBIx/Class/Storage/DBI.pm line 1016
	DBIx::Class::Storage::DBI::_populate_dbh(DBIx::Class::Storage::DBI::mysql=HASH(0x98e44d8)) called at /nfs/team112/perlbrew/perls/perl-5.14.2-farm3/lib/site_perl/5.14.2/DBIx/Class/Storage/DBI.pm line 915
	DBIx::Class::Storage::DBI::ensure_connected(DBIx::Class::Storage::DBI::mysql=HASH(0x98e44d8)) called at /nfs/team112/perlbrew/perls/perl-5.14.2-farm3/lib/site_perl/5.14.2/DBIx/Class/Storage/BlockRunner.pm line 209
	DBIx::Class::Storage::BlockRunner::__ANON__() called at /nfs/team112/perlbrew/perls/perl-5.14.2-farm3/lib/site_perl/5.14.2/Context/Preserve.pm line 37
	Context::Preserve::preserve_context(CODE(0xa27ebe0), "replace", CODE(0xa094bb0)) called at /nfs/team112/perlbrew/perls/perl-5.14.2-farm3/lib/site_perl/5.14.2/DBIx/Class/Storage/BlockRunner.pm line 221
	DBIx::Class::Storage::BlockRunner::_run(DBIx::Class::Storage::BlockRunner=HASH(0xa27eb08)) called at /nfs/team112/perlbrew/perls/perl-5.14.2-farm3/lib/site_perl/5.14.2/DBIx/Class/Storage/BlockRunner.pm line 112
	DBIx::Class::Storage::BlockRunner::run(DBIx::Class::Storage::BlockRunner=HASH(0xa27eb08)) called at /nfs/team112/perlbrew/perls/perl-5.14.2-farm3/lib/site_perl/5.14.2/DBIx/Class/Storage/DBI.pm line 811
	DBIx::Class::Storage::DBI::dbh_do(undef, undef, "SELECT COUNT( * ) FROM farmserver me WHERE ( id = ? )", ARRAY(0xa049ee0), ARRAY(0xa0bbe18)) called at /nfs/team112/perlbrew/perls/perl-5.14.2-farm3/lib/site_perl/5.14.2/DBIx/Class/Storage/DBI.pm line 1746
	DBIx::Class::Storage::DBI::_execute(DBIx::Class::Storage::DBI::mysql=HASH(0x98e44d8), "select", ARRAY(0xa07e098), ARRAY(0xa07e530), HASH(0x9c411f0), HASH(0xa0bbed8)) called at /nfs/team112/perlbrew/perls/perl-5.14.2-farm3/lib/site_perl/5.14.2/DBIx/Class/Storage/DBI.pm line 2307
	DBIx::Class::Storage::DBI::_select(DBIx::Class::Storage::DBI::mysql=HASH(0x98e44d8), ARRAY(0xa07e098), ARRAY(0xa07e530), HASH(0x9c411f0), HASH(0xa07e3f8)) called at /nfs/team112/perlbrew/perls/perl-5.14.2-farm3/lib/site_perl/5.14.2/DBIx/Class/Storage/DBI/Cursor.pm line 117
	DBIx::Class::Storage::DBI::Cursor::next(DBIx::Class::Storage::DBI::Cursor=HASH(0xa07e548)) called at /nfs/team112/perlbrew/perls/perl-5.14.2-farm3/lib/site_perl/5.14.2/DBIx/Class/ResultSetColumn.pm line 154
	DBIx::Class::ResultSetColumn::next(DBIx::Class::ResultSetColumn=HASH(0xa084660)) called at /nfs/team112/perlbrew/perls/perl-5.14.2-farm3/lib/site_perl/5.14.2/DBIx/Class/ResultSet.pm line 1615
	DBIx::Class::ResultSet::count(DBIx::Class::ResultSet=HASH(0xa07de40)) called at /nfs/team112_internal/production/prod_code/vr-pipe/modules/VRPipe/Persistent.pm line 1354
	VRPipe::Persistent::search(VRPipe::FarmServer=HASH(0xa0c2000), HASH(0x9c411f0)) called at /nfs/team112_internal/production/prod_code/vr-pipe/scripts/vrpipe-server line 329
	main::__ANON__() called at /nfs/team112/perlbrew/perls/perl-5.14.2-farm3/lib/site_perl/5.14.2/x86_64-linux/AnyEvent/Util.pm line 282
	eval {...} called at /nfs/team112/perlbrew/perls/perl-5.14.2-farm3/lib/site_perl/5.14.2/x86_64-linux/AnyEvent/Util.pm line 279
	AnyEvent::Util::_fork_schedule() called at /nfs/team112/perlbrew/perls/perl-5.14.2-farm3/lib/site_perl/5.14.2/x86_64-linux/AnyEvent/Util.pm line 321
	AnyEvent::Util::fork_call(CODE(0xa077aa0), CODE(0xa078268)) called at /nfs/team112_internal/production/prod_code/vr-pipe/scripts/vrpipe-server line 639
	main::__ANON__(EV::Periodic=SCALAR(0x5825af0), 512) called at /nfs/team112_internal/production/prod_code/vr-pipe/scripts/vrpipe-server line 668
	eval {...} called at /nfs/team112_internal/production/prod_code/vr-pipe/scripts/vrpipe-server line 668
	main::start_server() called at /nfs/team112_internal/production/prod_code/vr-pipe/scripts/vrpipe-server line 154
	main::start() called at /nfs/team112_internal/production/prod_code/vr-pipe/scripts/vrpipe-server line 92

**Comment by sb10** [comment]
Yes, use `vrpipe-server --max_submissions 999 [...]` if your MySQL server supports 1000 connections.

PS. I'd recommend switching from vrpipe to https://github.com/VertebrateResequencing/wr, which does not have these kinds of scaling problems. How easy that will be depends on how complex your pipelines are. I was thinking of doing a vrpipe pipeline -> wr compatability script if there was demand for it.
