### ISSUE TITLE
Is there a way to delete only files for withdrawn elements?

### ISSUE THREAD

**Issue by tnngh** [VertebrateResequencing/vr-pipe#28]
From line 163 in vrpipe-rm script
````
my $estates_pager    = $setup->dataelementstates_pager(include_withdrawn => 1);
````
it includes all elements whether they were withdrawn or not.  Is there an easy way using existing code/scripts to delete only files for withdrawn elements?

Or is the only way to edit the vrpipe-rm script to query for only the withdrawn elements:
````
my $estates_pager    = $setup->dataelementstates_pager(include_withdrawn => 1, only_withdrawn => 1);
````

**Comment by sb10** [comment]
You can edit the script or write your own to do exactly what you need. But if you just want to clean up everything to do with withdrawn data elements, you should use `vrpipe-setup --setup x --cleanup` instead.
